### ISSUE TITLE
AIDE removed from Arch Linux repositories

### ISSUE THREAD

**Issue by IJR222** [aide/aide.github.io#11]
The aide package was removed from Arch Linux's repositories, yet the website still lists it.

**Comment by hvhaugwitz** [comment]
That's unfortunate. What are the reasons for the removal?

**Comment by IJR222** [comment]
It's been orphaned, no one maintains it.

**Comment by originalnickname** [comment]
I can confirm.
```
$ sudo pacman -S aide
error: target not found: aide
```

it is still available in AUR but there the PGP key is wrong and I don't trust it.
So a trustworthy aide is not available for arch or manjaro anymore.

**Comment by hvhaugwitz** [comment]
@originalnickname What PGP key is wrong?
