### ISSUE TITLE
Aide on Mobian Pinephone pro

### ISSUE THREAD

**Issue by Emilio2801** [aide/aide.github.io#17]
I installed aide on Mobian. At the time of init with aideinit (aide --hint do not run) I get,after 4 minutes the following warnings:
lstat() failed for /run/use/1000/doc:permission denied
and
lstat()failed for /run/user/1000/gvfs:Permission denied
and I think it halts as for long no other indications.  The new data base is created but I think it is empty 
Can I do something or the program is not to be run on Mobian yet?

**Comment by Emilio2801** [comment]
Mobian on PinehonePro

**Comment by Zugschlus** [comment]
Looks like this file (and likely more) are protected in a way that even root cannot read it. Either find out why or exclude the file with a rule.

(I think this can be closed now)

**Comment by Emilio2801** [comment]
Ok
