### ISSUE TITLE
اتصال به درگاه پرداخت

### ISSUE THREAD

**Issue by arashd136300** [aide/aide.github.io#18]
سلام لطفا در مورد اتصال اپلیکیشن به درگاه پرداخت راهنمایی کنید ممنون میشم

**Comment by hvhaugwitz** [comment]
Please use English for communication in this project.

I close this issue for now, feel free to reopen it if it has translated to English.

**Comment by hvhaugwitz** [comment]
For the English version of this issue see #19.
