### ISSUE TITLE
AIDE mailing list archive is 403 Forbidden

### ISSUE THREAD

**Issue by imthenachoman** [aide/aide.github.io#2]
Not a bug with AIDE but I wasn't sure where to ask this. Is anyone else getting a 403 Forbidden when trying to access http://www.ipi.fi/pipermail/aide/?

**Comment by hvhaugwitz** [comment]
Yes, I also get a `403 Forbidden`.

I contacted the maintainer of the list about this issue.

**Comment by hvhaugwitz** [comment]
The Aide mailing list Archive is available again. Thanks for your notice.

**Comment by imthenachoman** [comment]
Thank you! Any plans to add search to the archives? It's rather difficult to search all of the archives for something.

**Comment by hvhaugwitz** [comment]
No, but you should be able to simply use a script to download the `Downloadable version`s from the Archive site to search the mailing list on your local machine.

**Comment by imthenachoman** [comment]
Yeah, I did that. Would be good to move to Google Groups so everything is searchable. Just an idea/thought. Thank you for your help!

**Comment by Zugschlus** [comment]
> Would be good to move to Google Groups so everything is searchable.

I veto that. Google Groups is among the five worst mailing list disservices ever invented.

**Comment by imthenachoman** [comment]
HAHA. It doesn't have to be Google Groups. I was just thinking any that let you search. But I'm also new to AIDE and I'm not about to make demands with how y'all manage it. It was just an idea. Feel free to crumple and trash. :)

I will hopefully get to finish building my server this weekend and trying AIDE. Wish me luck. :)

**Comment by PeterWhittaker** [comment]
FWIW, one can always use Google to search the mailing list - e.g., to search for all mentions of syslog, use:
`site:www.ipi.fi/pipermail/aide/ syslog`

**Comment by imthenachoman** [comment]
@PeterWhittaker Oh yeah. I always forget about that.
