### ISSUE TITLE
Old manual link is missing, what link should I give to users?

### ISSUE THREAD

**Issue by ShapeShifter499** [aide/aide.github.io#4]
The original link http://aide.sourceforge.net/stable/manual.html is broken. It's currently used as the link people should go to from https://wiki.archlinux.org/index.php/AIDE#Configuration  

I plan to update and fix that link. Where should I link the manual to?

**Comment by jdstrand** [comment]
The online manual was indeed useful and it would be good to resurrect it.

**Comment by sorin-mihai** [comment]
Since the manual is included in the source code (doc/manual.html), it could be mentioned in the main page and either included in this repository or linked from the main code repository, though I'm not sure how to achieve the later.

**Comment by hvhaugwitz** [comment]
I plan to rewrite the manual, until then I made the current version available now via https://aide.github.io/doc. This link should also be stable in the future.

**Comment by ShapeShifter499** [comment]
@hvhaugwitz Thank you for the fix. I love when things are well documented and it's easy to find information on how things should work. 

I fixed the link over at https://wiki.archlinux.org/index.php/AIDE#Configuration
